### ISSUE TITLE
Dodati teleport rupe

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG126-marble-maze#4]
Dodati 2 uparene rupe (na primer plave boje). Kada lopta upadne u jednu od uparenih rupa, pojavljuje se u drugoj od uparenih rupa.

**Comment by TamaraRado** [comment]
Dodate su dve plave rupe koje predstavljau teleporte. Prolaskom kroz jednu rupu igrac se pojavljuje na mestu druge rupe.
