### ISSUE TITLE
Dodati uslov za prolazak kroz cilj

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG126-marble-maze#5]
Dodati uslov da igrac mora da sakupi bar x (npr 100) poena pre nego sto moze skroz da se podigne kroz finalni cilindar. Ako ima manje od 100, napraviti animaciju gde krene da se dize gore i onda padne dole (pritom sto ima vise zivota treba da dostigne vecu visinu pre nego sto padne).

**Comment by TamaraRado** [comment]
Dodat je uslov da mora da se skupi bar 100 poena pre nego sto moze da se potpuno da se podigne kroz finalni cilindar. Ukoliko igrac ima manje poena kliker se podize na visinu koja je srazmerna broju poena i zatim pada. Igrac tada moze da nastavi sakljupanje poena
